### ISSUE TITLE
Make Teacher-Page #2 s UI to OneNote

### ISSUE THREAD

**Issue by Doemuu** [Dan6erbond/Im17A-Abschluss#35]
Close resemblance to OneNote since DSchneeberger is the person who got the school to use Computers. Especially OneNote was well promoted by him.

**Comment by Dan6erbond** [comment]
To copy OneNote's styling you can make use of React-Bootstrap's [tab component](https://react-bootstrap.netlify.app/components/tabs/). Additionally, make use of the custom tabs to have them vertically aligned on larger screens as such:
```html
<Tab.Container id="left-tabs-example" defaultActiveKey="first">
  <Row>
    <Col md={3} sm={12}>
      <Nav variant="pills" className="flex-column">
        <!-- Nav Items -->
      </Nav>
    </Col>
    <Col md={9} sm={12}>
      <Tab.Content>
        <!-- Tab Panes -->
      </Tab.Content>
    </Col>
  </Row>
</Tab.Container>
```
